kind: pipeline
type: docker
name: testing

trigger:
  event:
    - push
    - tag

steps:
- name: test
  image: golang:1.16
  commands:
  - go test -v ./...

- name: build
  image: golang:1.16
  commands:
  - go build .
